package params

var Status = []string{
	"1|Rpost=2;ret=\"no errcode\"|AC认证失败|AC authentication failure",
	"2|Rpost=2;ret=\"\"|SESSION已过期,请重新登录|The SESSION has been expired, please log in again",
	"3|Rpost=2;ret=\"Authentication Fail ErrCode=04\"|上网时…到上限|Online time / flow rate has been to the limit",
	"4|Rpost=2;ret=\"Authentication Fail ErrCode=05\"|您的账…了解具体原因，请访问自助服务系统。|Your account has been shut down",
	"5|Rpost=2;ret=\"Authentication Fail ErrCode=09\"|本账号…止使用|Online time / flow rate has been to the limit",
	"6|Rpost=2;ret=\"Authentication Fail ErrCode=11\"|不允许Radius登录|Not allow radius login",
	"7|Rpost=2;ret=\"Authentication Fail ErrCode=80\"|接入服务器不存在|Access to the server does not exist",
	"8|Rpost=2;ret=\"Authentication Fail ErrCode=81\"|LDAP认证失败|LDAP Authentication Failure",
	"9|Rpost=2;ret=\"Authentication Fail ErrCode=85\"|账号正在使用|Accounts are in use",
	"10|Rpost=2;ret=\"Authentication Fail ErrCode=86\"|绑定IP或MAC失败|IP or MAC Binding Fail",
	"11|Rpost=2;ret=\"Authentication Fail ErrCode=88\"|IP地址冲突|IP address conflict",
	"12|Rpost=2;ret=\"Authentication Fail ErrCode=94\"|接入服务器并发超限|Concurrent access to the server overrun",
	"13|err(2)|请在指定的登录源地址范围内登录|Please Login in at the specified source address range",
	"14|err(3)|请在指定的IP登录|Please login at the specified IP",
	"15|err(7)|请在指定的登录源VLAN范围登录|Please login in at specified Vlan scope",
	"16|err(10)|请在指定的Vlan登录|Please login at the specified Vlan",
	"17|err(11)|请在指定的MAC登录|Please login at the specified MAC",
	"18|err(17)|请在指定的设备端口登录|Please login with the specified equipment port",
	"19|userid error1|账号不存在|Account does not exist",
	"20|userid error2|密码错误|Password Error",
	"21|userid error3|密码错误|Password Error",
	"22|auth error4|用户使用量超出限制|Users to use more than limit",
	"23|auth error5|账号已停机|This account has been shut down",
	"24|auth error9|时长流量超支|Time length or flow overruns",
	"25|auth error80|本时段禁止上网|This time on the Internet is prohibited",
	"26|auth error99|用户名或密码错误|The user name or password mistake",
	"27|auth error198|用户名或密码错误|The user name or password mistake",
	"28|auth error199|用户名或密码错误|The user name or password mistake",
	"29|auth error258|账号只能在指定区域使用|This account can only be used in designated areas",
	"30|auth error|用户验证失败|Failed to authenticate user",
	"31|set_onlinet error|用户数超过限制|Users more than limit",
	"32|In use|登录超过人数限制|Log in more than limit",
	"33|port err|上课时间不允许上网|Class time is not allowed to access to the Internet",
	"34|can not use static ip|不允许使用静态IP|Can not use static ip",
	"35|[01], 本帐号只能在指定VLANID使用(0.4095)|本帐号只能在指定VLANID使用… account can only be used in the specified VLANID",
	"36|Mac, IP, NASip, PORT err(6)|本帐号只能在指定VLANID使用|Th… account can only be used in the specified VLANID",
	"37|Rpost=2;ret=\"wuxian OLno|VLAN范围控制账号的接入数量超出限制|VLAN range control account access limit exceeded",
	"38|Oppp error: 1|运营商账号密码错误，错误码为：1|Operator account password error, error code: 1",
	"39|Oppp error: 5|运营商账号在线，错误码为：5|Operator account online, error code: 5",
	"40|Oppp error: 18|运营商账号密码错误，错误码为：18|Operator account password error, error code: 18",
	"41|Oppp error: 21|运营商账号在线，错误码为：21|Operator account online, error code: 21",
	"42|Oppp error: 26|运营商账号被绑定，错误码为：26|Operator account online, error code: 21",
	"43|Oppp error: 29|运营商账号锁定的用户端口NAS-Port-Id错误，错误码为：29|Operator account online, error code: 21",
	"44|Oppp error: userid inuse|运营商账号已被使用|Operator account has been used",
	"45|Oppp error: cant find user|运营商账号无法获取或不存在|Opera…r account could not be obtained or does not exist",
	"46|bind userid error|绑定运营商账号失败|Bind operator account failed",
	"47|Oppp error: TOO MANY CONNECTIONS|运营商账号在线|Operator account online",
	"48|Oppp error: Timeout|运营商账号状态异常(欠费等)|Operator account status abnormal(arrears, etc.)",
	"49|Oppp error: User dial-in so soon|运营商账号刚下线|Operator account just off the assembly line",
}
